[package]
name    = "GmpExample"
version = "0.1.0"
edition = "2024"

[dependencies]
# Only your CGP-Sui sources here:
AxelarGateway    = { git = "https://github.com/axelarnetwork/axelar-cgp-sui.git", rev = "b35227a82f7ca6f941a7e729e1a3b3d48a64b982", subdir = "move/axelar_gateway" }
GasService       = { git = "https://github.com/axelarnetwork/axelar-cgp-sui.git", rev = "b35227a82f7ca6f941a7e729e1a3b3d48a64b982", subdir = "move/gas_service" }
RelayerDiscovery = { git = "https://github.com/axelarnetwork/axelar-cgp-sui.git", rev = "b35227a82f7ca6f941a7e729e1a3b3d48a64b982", subdir = "move/relayer_discovery" }
Utils            = { git = "https://github.com/axelarnetwork/axelar-cgp-sui.git", rev = "b35227a82f7ca6f941a7e729e1a3b3d48a64b982", subdir = "move/utils" }
VersionControl   = { git = "https://github.com/axelarnetwork/axelar-cgp-sui.git", rev = "b35227a82f7ca6f941a7e729e1a3b3d48a64b982", subdir = "move/version_control" }

[addresses]
# 1) Your own module alias must match your Move source exactly (case-sensitive)
GmpExample        = "0x0"

# 2) All CGP-Sui packages point at their live testnet IDs
AxelarGateway     = "0x6ddfcdd14a1019d13485a724db892fa0defe580f19c991eaabd690140abb21e4"
GasService        = "0xddf711b99aec5c72594e5cf2da4014b2d30909850a759d2e8090add1088dbbc9" 
RelayerDiscovery  = "0x2f871726329f555bc3fa6eec129f259a8bce3cb3989b39dd75a627a1a0961bc2"
Utils             = "0x9d817589ae367cc3f3bc9ca40394be79e5853bfca98014f27acfd4da9db78421"
VersionControl    = "0x6e8ebd241a5b89499e0cd104540f8025af111dcd42644bb732dbc170e395ce0c"
